apiVersion: apps/v1
kind: Deployment
metadata:
  name: beanstalkd
spec:
  selector:
    matchLabels:
      app: beanstalkd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: beanstalkd
    spec:
      containers:
      - image: efantasy-beanstalkd
        imagePullPolicy: IfNotPresent
        name: beanstalkd
        ports:
        - containerPort: 11300
          name: beanstalkd
