apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: notifications-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - image: esportsdrafts-notifications
          name: notifications
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: ENV
          envFrom:
            - configMapRef:
                name: config
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: local-testing-inbox
              mountPath: /inbox
      volumes:
        - name: local-testing-inbox
          hostPath:
            # TODO: This will only support OS X right now
            # Linux needs to mount /home/inbox
            path: /Users/inbox

