apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
  namespace: default
  labels:
    service: notifications
    app.kubernetes.io/managed-by: tilt
spec:
  replicas: 1
  selector:
    matchLabels:
      service: notifications
      app.kubernetes.io/managed-by: tilt
  template:
    metadata:
      labels:
        service: notifications
    spec:
      containers:
        - image: esportsdrafts-notifications
          name: notifications
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: ENV
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: BASE_URL
          envFrom:
            - configMapRef:
                name: config
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: local-testing-inbox
              mountPath: /inbox
      volumes:
        - name: local-testing-inbox
          hostPath:
            # TODO: This will only support OS X right now
            # Linux needs to mount /home/inbox
            path: /Users/inbox
