apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: notifications-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - image: efantasy-notifications
          name: notifications
          ports:
            - containerPort: 8000
