
FROM docker.pkg.github.com/barreyo/esportsdrafts/esportsdrafts-python:11-13-2019

COPY requirements.txt .
RUN python3 -m pip install -r requirements.txt

COPY requirements-dev.txt .
RUN python3 -m pip install -r requirements-dev.txt

COPY Makefile .
COPY tests/ .
