
FROM docker.pkg.github.com/barreyo/esportsdrafts/esportsdrafts-python:11-13-2019

ARG VERSION=unknown

LABEL Name "esportsdrafts-testing"
LABEL Version ${VERSION}

COPY requirements.txt requirements-dev.txt ./
RUN apk --no-cache add --virtual .build-deps gcc musl-dev linux-headers \
    && python3 -m pip install -r requirements.txt \
    && python3 -m pip install -r requirements-dev.txt \
    && apk del .build-deps \
    && rm -rf /var/cache/apk/* \
    && rm -rf /tmp/*

COPY Makefile .
COPY tests/ .
