apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/enable-modsecurity: "true"
    ingress.kubernetes.io/enable-owasp-core-rules: "true"
spec:
  tls:
    - hosts:
      - api.efantasy.dev
      - efantasy.dev
      secretName: tls-certificate
  rules:
  - host: efantasy.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 8000
  - host: api.efantasy.dev
    http:
      paths:
      - path: /v1/auth
        backend:
          serviceName: auth
          servicePort: 8000
