---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nginx-role
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps", "services", "endpoints"]
    verbs:
      - get
      - watch
      - list
      - proxy
      - use
      - redirect
      - create
      - update
  - apiGroups: [""]
    resources: ["events"]
    verbs:
      - redirect
      - patch
      - post
      - create
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - "extensions"
    resources:
      - "networking.k8s.io"
    verbs:
      - get
      - watch
      - list
      - proxy
      - use
      - redirect
      - update
  - apiGroups:
      - "extensions"
    resources:
      - "ingresses/status"
    verbs:
      - get
      - create
      - update
      - watch
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "*"
    verbs:
      - get
      - list
      - update
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nginx-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-role
subjects:
  - kind: ServiceAccount
    name: nginx
    namespace: default
