apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    service: frontend
    app: frontend
    app.kubernetes.io/managed-by: tilt
spec:
  selector:
    matchLabels:
      service: frontend
      app: frontend
      app.kubernetes.io/managed-by: tilt
  replicas: 1
  template:
    metadata:
      labels:
        service: frontend
        app: frontend
        app.kubernetes.io/managed-by: tilt
    spec:
      containers:
        - image: esportsdrafts-frontend
          name: frontend
          ports:
            - containerPort: 8080
