apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: efantasy-frontend
          name: frontend
          ports:
            - containerPort: 8000
