apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    service: mysql
    app.kubernetes.io/managed-by: tilt
spec:
  selector:
    matchLabels:
      service: mysql
      app.kubernetes.io/managed-by: tilt
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: mysql
        app.kubernetes.io/managed-by: tilt
    spec:
      containers:
        - image: esportsdrafts-mysql
          imagePullPolicy: IfNotPresent
          name: mysql
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          # volumeMounts:
          # - name: mysql-persistent-storage
          # mountPath: /var/lib/mysql
      # volumes:
      # - name: mysql-persistent-storage
      # persistentVolumeClaim:
      # claimName: mysql-pv-claim
