apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: default
  labels:
    service: auth
    app: auth
    app.kubernetes.io/managed-by: tilt
spec:
  replicas: 1
  selector:
    matchLabels:
      service: auth
      app: auth
      app.kubernetes.io/managed-by: tilt
  template:
    metadata:
      labels:
        service: auth
        app: auth
        app.kubernetes.io/managed-by: tilt
    spec:
      containers:
        - image: esportsdrafts-auth
          name: auth
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: config
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: ENV
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: jwt_key

          livenessProbe:
            httpGet:
              path: /live
              port: 8086
            initialDelaySeconds: 5
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /ready
              port: 8086
            periodSeconds: 5
