apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: efantasy-auth
          name: auth
          ports:
            - containerPort: 8000
          env:
            - name: JWT_KEY
              value: "string_for_local_test_update_me"

          livenessProbe:
            httpGet:
              path: /live
              port: 8086
            initialDelaySeconds: 5
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /ready
              port: 8086
            periodSeconds: 5

