apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: "efantasy-auth:v0.0.0-6-gbf962e3878"
          imagePullPolicy: IfNotPresent
          name: auth
          ports:
            - containerPort: 8000
